class AmanahQueueCardData {
  const AmanahQueueCardData({
    required this.id,
    required this.queueNumber,
    required this.patientName,
    required this.complaint,
    required this.poly,
    required this.doctorName,
    required this.doctorImage,
    required this.priority,
    required this.timeSlot,
    required this.age,
    required this.gender,
    this.room = 'R. Periksa 101',
    this.status = 'Menunggu',
    this.watermarkAsset = 'assets/amanah/id_card/images/wm.svg',
    this.guardian,
  });

  final String id;
  final String queueNumber;
  final String patientName;
  final String complaint;
  final String poly;
  final String doctorName;
  final String doctorImage;
  final String priority;
  final String timeSlot;
  final int age;
  final String gender;
  final String room;
  final String status;
  final String watermarkAsset;
  final String? guardian;

  String get patientRm => 'RM-2026-${queueNumber.replaceAll('#', '').padLeft(4, '0')}';
}

const List<AmanahQueueCardData> defaultAmanahQueueCards = <AmanahQueueCardData>[
  AmanahQueueCardData(
    id: 'queue-01',
    queueNumber: '#01',
    patientName: 'Budi Mulyono',
    complaint: 'sakit kepala dan panas dalam',
    poly: 'Poli gigi',
    doctorName: 'dr. Sarah Wijaya, Sp.A',
    doctorImage: 'assets/amanah/id_card/images/woman-docter-3.png',
    priority: 'Reguler',
    timeSlot: '08:30 WIB',
    age: 34,
    gender: 'L',
    room: 'R. Periksa 101',
    status: 'Menunggu',
  ),
  AmanahQueueCardData(
    id: 'queue-02',
    queueNumber: '#02',
    patientName: 'Siti Rahmawati',
    complaint: 'Pemeriksaan rutin anak & flu batuk',
    poly: 'Poli Anak',
    doctorName: 'dr. Sarah Wijaya, Sp.A',
    doctorImage: 'assets/amanah/id_card/images/woman-docter-3.png',
    priority: 'Prioritas',
    timeSlot: '08:45 WIB',
    age: 6,
    gender: 'P',
    room: 'R. Anak 104',
    status: 'Menunggu',
  ),
  AmanahQueueCardData(
    id: 'queue-03',
    queueNumber: '#03',
    patientName: 'Ahmad Fauzi',
    complaint: 'Kontrol hipertensi berkala & vertigo',
    poly: 'Poli Umum',
    doctorName: 'dr. Sarah Wijaya, Sp.A',
    doctorImage: 'assets/amanah/id_card/images/woman-docter-3.png',
    priority: 'BPJS',
    timeSlot: '09:00 WIB',
    age: 52,
    gender: 'L',
    room: 'R. Umum 102',
    status: 'Menunggu',
  ),
  AmanahQueueCardData(
    id: 'queue-04',
    queueNumber: '#04',
    patientName: 'Dewi Sartika',
    complaint: 'Konsultasi gusi bengkak & cabut gigi',
    poly: 'Poli Gigi',
    doctorName: 'dr. Sarah Wijaya, Sp.A',
    doctorImage: 'assets/amanah/id_card/images/woman-docter-3.png',
    priority: 'Reguler',
    timeSlot: '09:15 WIB',
    age: 28,
    gender: 'P',
    room: 'R. Gigi 201',
    status: 'Menunggu',
  ),
  AmanahQueueCardData(
    id: 'queue-05',
    queueNumber: '#05',
    patientName: 'Hendra Wijaya',
    complaint: 'Nyeri lambung akut kronis & mual',
    poly: 'Poli Penyakit Dalam',
    doctorName: 'dr. Sarah Wijaya, Sp.A',
    doctorImage: 'assets/amanah/id_card/images/woman-docter-3.png',
    priority: 'Prioritas',
    timeSlot: '09:30 WIB',
    age: 41,
    gender: 'L',
    room: 'R. Interna 105',
    status: 'Menunggu',
  ),
  AmanahQueueCardData(
    id: 'queue-06',
    queueNumber: '#06',
    patientName: 'Rina Marlina',
    complaint: 'Pemeriksaan USG kandungan & trimester 2',
    poly: 'Poli Obgyn',
    doctorName: 'dr. Sarah Wijaya, Sp.A',
    doctorImage: 'assets/amanah/id_card/images/woman-docter-3.png',
    priority: 'VIP',
    timeSlot: '09:45 WIB',
    age: 30,
    gender: 'P',
    room: 'R. Obgyn 203',
    status: 'Menunggu',
  ),
  AmanahQueueCardData(
    id: 'queue-07',
    queueNumber: '#07',
    patientName: 'Agus Setiawan',
    complaint: 'Alergi dingin, gatal kemerahan & ruam kulit',
    poly: 'Poli Kulit',
    doctorName: 'dr. Sarah Wijaya, Sp.A',
    doctorImage: 'assets/amanah/id_card/images/woman-docter-3.png',
    priority: 'Reguler',
    timeSlot: '10:00 WIB',
    age: 24,
    gender: 'L',
    room: 'R. Kulit 108',
    status: 'Menunggu',
  ),
  AmanahQueueCardData(
    id: 'queue-08',
    queueNumber: '#08',
    patientName: 'Nurul Hidayah',
    complaint: 'Pemeriksaan mata buram & resep kacamata',
    poly: 'Poli Mata',
    doctorName: 'dr. Sarah Wijaya, Sp.A',
    doctorImage: 'assets/amanah/id_card/images/woman-docter-3.png',
    priority: 'BPJS',
    timeSlot: '10:15 WIB',
    age: 38,
    gender: 'P',
    room: 'R. Mata 106',
    status: 'Menunggu',
  ),
  AmanahQueueCardData(
    id: 'queue-09',
    queueNumber: '#09',
    patientName: 'Eko Prasetyo',
    complaint: 'Nyeri persendian lutut & cek asam urat',
    poly: 'Poli Saraf',
    doctorName: 'dr. Sarah Wijaya, Sp.A',
    doctorImage: 'assets/amanah/id_card/images/woman-docter-3.png',
    priority: 'Reguler',
    timeSlot: '10:30 WIB',
    age: 49,
    gender: 'L',
    room: 'R. Saraf 107',
    status: 'Menunggu',
  ),
  AmanahQueueCardData(
    id: 'queue-10',
    queueNumber: '#10',
    patientName: 'Maya Kusuma',
    complaint: 'Medical check-up berkala & tes lab darah',
    poly: 'Poli Umum',
    doctorName: 'dr. Sarah Wijaya, Sp.A',
    doctorImage: 'assets/amanah/id_card/images/woman-docter-3.png',
    priority: 'VIP',
    timeSlot: '10:45 WIB',
    age: 32,
    gender: 'P',
    room: 'R. Executive 205',
    status: 'Menunggu',
  ),
];
